# Generated by Django 4.1.3 on 2022-11-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_userprofuile_currently_hacking_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blogs_image', models.ImageField(blank=True, upload_to='blog-image/')),
            ],
        ),
    ]
