# Generated by Django 4.1.3 on 2022-11-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blogs_image',
        ),
        migrations.AddField(
            model_name='blogs',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
