# Generated by Django 4.1.3 on 2022-11-30 09:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blogs_image', models.ImageField(blank=True, upload_to='blog-image/')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('time_upload', models.DateTimeField(auto_now_add=True)),
                ('mini_description', models.TextField(null=True)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(blank=True, max_length=1000, null=True)),
                ('read', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='technology', max_length=250)),
                ('images', models.ImageField(null=True, upload_to='Category-images')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('e_mail', models.EmailField(max_length=250)),
                ('phone_number', models.IntegerField()),
                ('contact_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Write your comment')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='Blog_category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.blog_category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
