# Generated by Django 4.1.3 on 2022-12-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blog_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_popular',
            field=models.CharField(choices=[('pending', 'pending'), ('Read', 'Read')], max_length=10),
        ),
    ]
